adventures/urls.py
from django.urls import path
from . import views
app_name = 'adventures'
urlpatterns = [
    # adventure_location views
    path('', views.home, name='home'),
    path('about', views.about, name='about'),
    path('contact', views.contact, name='contact'),
    path('help', views.help, name='help'),
    path('locations', views.adventure_location_list, name='adventure_location_list'),
    path('trips', views.adventure_trip_list, name='adventure_trip_list'),
    path('locations/<int:location_id>', views.adventure_location_detail, name='adventure_location_detail'),
    path('locations/adventure-creator', views.adventure_creator, name='adventure_creator'),
    path('locations/<int:location_id>/trip-creator', views.trip_creator, name='trip_creator'),
    path('locations/adventure-editor/<int:location_id>', views.edit_location, name='edit_location'),
    path('locations/delete-location/<int:location_id>', views.delete_location, name='delete_location'),
]

djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('adventures/', include('adventures.urls', namespace='views')),
    path('users/', include('users.urls', namespace='users')),
    path('reviews/', include('reviews.urls', namespace='reviews')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views
app_name = 'users'
urlpatterns = [
    # adventure_location views
    path('register/', views.register, name='register'),
    path('profile/<str:username>', views.profile, name='profile'),
    path('login', views.login_user, name='login'),
    path('logout', views.logout_user, name='logout'),
    path('list/', views.user_list, name='list'),
    path('edit/<str:username>', views.edit_user, name='edit'),
]

adventures/models.py
import datetime

from django.db import models
from django.contrib.auth.models import User
from datetime import datetime


# Create your models here.
from django.urls import reverse


class AdventureLocation(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    author = models.CharField(max_length=30)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    rating = models.FloatField(default=5)
    num_reviews = models.IntegerField(default=0)
    img = models.CharField(max_length=100, default='')
    alt = models.CharField(max_length=100)
    date = models.DateTimeField(default=datetime.now)
    summary = models.TextField(default='')


    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('adventures:adventure_location_detail', args=[self.id])

class Review(models.Model):
    adventureLocation = models.ForeignKey(AdventureLocation, on_delete=models.CASCADE)
    author = models.CharField(max_length=30)
    date = models.DateTimeField(default=datetime.now)
    review = models.TextField()
    rating = models.FloatField(default=5)

    def __str__(self):
        return self.author

class AdventureTrip(models.Model):
    adventureLocation = models.ForeignKey(AdventureLocation, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    description = models.TextField()
    author = models.CharField(max_length=30)
    date = models.DateTimeField(default=datetime.now)
    summary = models.TextField(default='')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('adventures:adventure_location_detail', args=[self.id])

adventures/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.template.loader import render_to_string

from .models import AdventureLocation, AdventureTrip, Review, User
from actions.models import Action
from django.http import JsonResponse
from azure.ai.textanalytics import TextAnalyticsClient
from azure.core.credentials import AzureKeyCredential
from azure.core.credentials import AzureKeyCredential
from azure.ai.textanalytics import (
    TextAnalyticsClient,
    ExtractSummaryAction
)
import requests

# Create your views here.
def adventure_location_list(request):
    is_ajax = request.headers.get('x-requested-with') == 'XMLHttpRequest'
    orderType = request.GET.get('orderType')
    queryString = request.GET.get('queryString')

    #if orderType exists, then create new ordered querySet
    if orderType:
        adventure_locations = AdventureLocation.objects.all().order_by(orderType)

    elif queryString:
        adventure_locations = AdventureLocation.objects.all().filter(name__icontains=queryString)

    # Else, default to order by name ascending
    else:
        adventure_locations = AdventureLocation.objects.all().order_by("name")

    if is_ajax:
        if request.method == 'GET':

            # if ajax, then render the locations section to html with new ordered locations
            htmlToRender = render_to_string(
                template_name='adventures/adventure_location/locations_results.html', context={'adventure_locations': adventure_locations}
            )
            data_dict = {'html_from_view': htmlToRender, 'success': 'success'}
            return JsonResponse(data=data_dict, safe=False, status=200)

        else:
            return JsonResponse({'error': 'Invalid Ajax request.'}, status=400)


    return render(request, 'adventures/adventure_location/list.html', {'adventure_locations': adventure_locations})


# List view for trips
def adventure_trip_list(request):
    is_ajax = request.headers.get('x-requested-with') == 'XMLHttpRequest'
    queryString = request.GET.get('queryString')


    if queryString:
        adventure_trips = AdventureTrip.objects.all().filter(name__icontains=queryString)

    # Else, default to order by name ascending
    else:
        adventure_trips = AdventureTrip.objects.all().order_by("-date")

    if is_ajax:
        if request.method == 'GET':

            # if ajax, then render the locations section to html with new ordered locations
            htmlToRender = render_to_string(
                template_name='adventures/adventure_location/trips_results.html',
                context={'adventure_trips': adventure_trips},
            )
            data_dict = {'html_from_view': htmlToRender, 'success': 'success'}
            return JsonResponse(data=data_dict, safe=False, status=200)

        else:
            return JsonResponse({'error': 'Invalid Ajax request.'}, status=400)


    return render(request, 'adventures/adventure_location/list_trips.html', {'adventure_trips': adventure_trips})


# View for detail view
def adventure_location_detail(request, location_id):
    locations_list = AdventureLocation.objects.all()
    is_ajax = request.headers.get('x-requested-with') == 'XMLHttpRequest'
    for location in locations_list:
        if (location.id == location_id):
            break

    reviews = Review.objects.filter(adventureLocation__id=location.id).order_by('-date')
    trips = AdventureTrip.objects.filter(adventureLocation__id=location.id).order_by('-date')

    if is_ajax:
        if request.method == 'POST':

            adventureId = request.POST.get('adventureId')
            review = request.POST.get('review')
            rating = request.POST.get('rating')
            theAdventure = AdventureLocation.objects.get(pk=adventureId)

            # Create a new Review object and add to DB
            nr = Review(
                adventureLocation=theAdventure,
                author=request.session.get('username'),
                review=review,
                rating=rating,
            )
            nr.save()

            # Update location review count
            location.num_reviews = location.num_reviews + 1
            location.save()


            # Log the action
            user = User.objects.get(username=request.session.get('username'))
            action = Action(
                user=user,
                verb="left a new review on:",
                target=theAdventure,
            )
            action.save()

            # Render the review section as html to send as response
            htmlToRender = render_to_string(
                template_name='adventures/adventure_location/location_detail_review.html', context={'reviews': reviews}
            )
            data_dict = {'html_from_view': htmlToRender, 'success': 'success'}
            return JsonResponse(data=data_dict, safe=False, status=200)

        else:
            return JsonResponse({'error': 'Invalid Ajax request.'}, status=400)

    return render(request,
                  'adventures/adventure_location/detail.html',
                  {
                      'location': location,
                      'adventure_trips': trips,
                      'reviews': reviews,
                  },
                  )


# View for search function
def adventure_location_search(request):
    return render(request,
                  'adventures/adventure_location/search.html',
                  )


# View for results page
def adventure_search_results(request):
    return render(request,
                  'adventures/adventure_location/search_results.html',
                  )


# Authenticate the client using your key and endpoint
def authenticate_client():
    ta_credential = AzureKeyCredential(key)
    text_analytics_client = TextAnalyticsClient(
            endpoint=endpoint,
            credential=ta_credential)
    return text_analytics_client


# View for adding location
def adventure_creator(request):
    # Redirect if not logged in
    if not request.session.get('username', False):
        return redirect('adventures:home')

    if request.method == 'POST':
        # Process the form
        main_image = request.POST.get('locationMainImage')
        name = request.POST.get('locationName')
        description = request.POST.get('locationDescription')
        alt = request.POST.get('mainImageAlt')

        # Check the data - content moderation
        endpoint = 'https://cs5774lang.cognitiveservices.azure.com/'
        key = '238baa4bb2154b73854657d97d4f244a'

        # Authenticate the client using your key and endpoint
        def authenticate_client():
            ta_credential = AzureKeyCredential(key)
            text_analytics_client = TextAnalyticsClient(
                endpoint=endpoint,
                credential=ta_credential)
            return text_analytics_client

        client = authenticate_client()

        # document to analyze
        document = [description]

        # analyze the data
        poller = client.begin_analyze_actions(
            document,
            actions=[
                ExtractSummaryAction(MaxSentenceCount=2)
            ],
        )

        # Make result into a summary
        document_results = poller.result()
        for result in document_results:
            extract_summary_result = result[0]  # first document, first result
            if extract_summary_result.is_error:
                print("...Is an error with code '{}' and message '{}'".format(
                    extract_summary_result.code, extract_summary_result.message
                ))
            else:
                response = " ".join([sentence.text for sentence in extract_summary_result.sentences])

        user = User.objects.get(username=request.session.get('username'))

        al = AdventureLocation(
            name=name,
            description=description,
            author=request.session.get('username'),
            user=user,
            img=main_image,
            alt=alt,
            summary=response,
        )
        al.save()

        # Log the action
        action = Action(
            user=user,
            verb="created the adventure location:",
            target=al,
        )
        action.save()

        messages.add_message(
            request,
            messages.SUCCESS,
            "You successfully created a new location: %s" % al.name,
        )
        return redirect('adventures:adventure_location_detail', al.id)

    else:
        # show the form
        return render(request,
                      'adventures/adventure_location/creator.html',
                      )

# View for adding trip
def trip_creator(request, location_id):
    # Redirect if not logged in
    if not request.session.get('username', False):
        return redirect('adventures:home')

    location = AdventureLocation.objects.get(id=location_id)

    if request.method == 'POST':
        # Process the form
        date = request.POST.get('date')
        name = request.POST.get('tripName')
        description = request.POST.get('tripDescription')

        # Check the data - content moderation
        endpoint = 'https://cs5774lang.cognitiveservices.azure.com/'
        key = '238baa4bb2154b73854657d97d4f244a'

        # Authenticate the client using your key and endpoint
        def authenticate_client():
            ta_credential = AzureKeyCredential(key)
            text_analytics_client = TextAnalyticsClient(
                endpoint=endpoint,
                credential=ta_credential)
            return text_analytics_client

        client = authenticate_client()

        # document to analyze
        document = [description]

        # analyze the data
        poller = client.begin_analyze_actions(
            document,
            actions=[
                ExtractSummaryAction(MaxSentenceCount=2)
            ],
        )

        # Make result into a summary
        document_results = poller.result()

templates/adventures/base.html
{% load static %}
<!doctype html>
<html lang="en">
    <head>
      <meta charset="utf-8">
        <title>Fido&Student Adventures | {% block page-title %}{% endblock %} </title>
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <script src="{% static "js/jquery-3.6.0.min.js" %}"></script>
      <script src="{% static "js/scripts.js" %}"></script>
      <link rel="stylesheet" type="text/css" href="{% static "css/responsive.css" %}">
    </head>

    <body>

        <!-- The header section of the page-->
        <div id="header">

          <!--The Logo and Main Title-->
          <div id="title-main">
            <img src="{% static "media/dog.svg" %}" alt="logo">
            <div>
              <h1>Fido&Student Adventures</h1>
            </div>
          </div>

          <!-- top-right logged-in status -->

                <!-- Display only if user logged in -->
              {% if request.session.username %}
                  <div id="login-box">
                    <form id="login-box-form">
                        <p>Logged in as <a href="{% url 'users:profile' request.session.username %}"><strong
                        >{{ request.session.username }}</strong></a> |
                            <a
                                href="
{% url 'users:logout' %}">Log
                            out</a></p>
                    </form>
                  </div>

                  <!-- Else, display this for logged out users -->
              {% else %}
                    <div id="login-box">
                        <form id="login-box-form" action="{% url 'users:login' %}" method="POST">
                            {% csrf_token %}
                            <input type="text" name="username" placeholder="Username" required>
                            <input type="password" name="password" placeholder="Password" required>
                            <input type="submit" name="login" value="Log In"> or <a href="{% url 'users:register' %}">Sign Up</a>
                        </form>
                    </div>

              {% endif %}

          <!-- Main Navigation-->
          <nav id="nav-main">
            <ul>
                <li><a href="{% url 'adventures:home' %}">Home</a></li>
                <li><a href="{% url 'adventures:adventure_location_list' %}">Adventures</a></li>
                {% if request.session.username %}
                    <li><a href="{% url 'adventures:adventure_trip_list' %}">Trips</a></li>
                {% endif %}
                <li><a href="{% url 'adventures:about' %}">About</a></li>
                <li><a href="{% url 'adventures:contact' %}">Contact</a></li>
                {% if request.session.username %}
                    <li><a href="{% url 'users:profile' request.session.username %}">Profile</a></li>
                {% endif %}
                {% if request.session.role == 'admin' %}
                    <li><a href="{% url 'users:list' %}">Edit Users</a></li>
                {% endif %}
            </ul>
          </nav>

        </div> <!-- End header-->

        <!-- Content Section of the page-->
        <div id="content">

            {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}

            <!-- The search Section-->
          <div id ="searchAdventures">
              {% block search-features %}{% endblock %}
          </div>

        <!-- Block for child templates to use for page content -->
        {% block content %}

        {% endblock %}

        </div> <!-- End Content -->

        <!-- The Footer section of the page-->
        <div id="footer">

          <!-- The Footer navigation -->
          <nav id="nav-footer">
            <ul>
              <li><a href="{% url 'adventures:home' %}">Home</a></li>
              <li><a href="{% url 'adventures:about' %}">About</a></li>
              <li><a href="{% url 'adventures:contact' %}">Contact</a></li>
                {% if request.session.username %}
                    <li><a href="{% url 'users:profile' request.session.username %}">Profile</a></li>
                {% endif %}
              <li><a href="{% url 'adventures:help' %}">Help</a></li>
            </ul>
          </nav>
        </div> <!-- End Footer-->

      </body>
    </html>