adventures/urls.py
from django.urls import path
from . import views
app_name = 'adventures'
urlpatterns = [
    # adventure_location views
    path('', views.home, name='home'),
    path('about', views.about, name='about'),
    path('contact', views.contact, name='contact'),
    path('help', views.help, name='help'),
    path('locations', views.adventure_location_list, name='adventure_location_list'),
    path('trips', views.adventure_trip_list, name='adventure_trip_list'),
    path('locations/<int:location_id>', views.adventure_location_detail, name='adventure_location_detail'),
    path('locations/adventure-creator', views.adventure_creator, name='adventure_creator'),
    path('locations/<int:location_id>/trip-creator', views.trip_creator, name='trip_creator'),
    path('locations/adventure-editor/<int:location_id>', views.edit_location, name='edit_location'),
    path('locations/delete-location/<int:location_id>', views.delete_location, name='delete_location'),
]

djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('adventures/', include('adventures.urls', namespace='views')),
    path('users/', include('users.urls', namespace='users')),
    path('reviews/', include('reviews.urls', namespace='reviews')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views
app_name = 'users'
urlpatterns = [
    # adventure_location views
    path('register/', views.register, name='register'),
    path('profile/<str:username>', views.profile, name='profile'),
    path('login', views.login_user, name='login'),
    path('logout', views.logout_user, name='logout'),
    path('list/', views.user_list, name='list'),
    path('edit/<str:username>', views.edit_user, name='edit'),
]

adventures/models.py
import datetime

from django.db import models
from django.contrib.auth.models import User
from datetime import datetime


# Create your models here.
from django.urls import reverse


class AdventureLocation(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    author = models.CharField(max_length=30)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    rating = models.FloatField(default=5)
    num_reviews = models.IntegerField(default=0)
    img = models.CharField(max_length=100, default='')
    alt = models.CharField(max_length=100)
    date = models.DateTimeField(default=datetime.now)
    summary = models.TextField(default='')


    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('adventures:adventure_location_detail', args=[self.id])

class Review(models.Model):
    adventureLocation = models.ForeignKey(AdventureLocation, on_delete=models.CASCADE)
    author = models.CharField(max_length=30)
    date = models.DateTimeField(default=datetime.now)
    review = models.TextField()
    rating = models.FloatField(default=5)

    def __str__(self):
        return self.author

class AdventureTrip(models.Model):
    adventureLocation = models.ForeignKey(AdventureLocation, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    description = models.TextField()
    author = models.CharField(max_length=30)
    date = models.DateTimeField(default=datetime.now)
    summary = models.TextField(default='')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('adventures:adventure_location_detail', args=[self.id])

adventures/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.template.loader import render_to_string

from .models import AdventureLocation, AdventureTrip, Review, User
from actions.models import Action
from django.http import JsonResponse
from azure.ai.textanalytics import TextAnalyticsClient
from azure.core.credentials import AzureKeyCredential
from azure.core.credentials import AzureKeyCredential
from azure.ai.textanalytics import (
    TextAnalyticsClient,
    ExtractSummaryAction
)
import requests

# Create your views here.
def adventure_location_list(request):
    is_ajax = request.headers.get('x-requested-with') == 'XMLHttpRequest'
    orderType = request.GET.get('orderType')
    queryString = request.GET.get('queryString')

    #if orderType exists, then create new ordered querySet
    if orderType:
        adventure_locations = AdventureLocation.objects.all().order_by(orderType)

    elif queryString:
        adventure_locations = AdventureLocation.objects.all().filter(name__icontains=queryString)

    # Else, default to order by name ascending
    else:
        adventure_locations = AdventureLocation.objects.all().order_by("name")

    if is_ajax:
        if request.method == 'GET':

            # if ajax, then render the locations section to html with new ordered locations
            htmlToRender = render_to_string(
                template_name='adventures/adventure_location/locations_results.html', context={'adventure_locations': adventure_locations}
            )
            data_dict = {'html_from_view': htmlToRender, 'success': 'success'}
            return JsonResponse(data=data_dict, safe=False, status=200)

        else:
            return JsonResponse({'error': 'Invalid Ajax request.'}, status=400)


    return render(request, 'adventures/adventure_location/list.html', {'adventure_locations': adventure_locations})


# List view for trips
def adventure_trip_list(request):
    is_ajax = request.headers.get('x-requested-with') == 'XMLHttpRequest'
    queryString = request.GET.get('queryString')


    if queryString:
        adventure_trips = AdventureTrip.objects.all().filter(name__icontains=queryString)

    # Else, default to order by name ascending
    else:
        adventure_trips = AdventureTrip.objects.all().order_by("-date")

    if is_ajax:
        if request.method == 'GET':

            # if ajax, then render the locations section to html with new ordered locations
            htmlToRender = render_to_string(
                template_name='adventures/adventure_location/trips_results.html',
                context={'adventure_trips': adventure_trips},
            )
            data_dict = {'html_from_view': htmlToRender, 'success': 'success'}
            return JsonResponse(data=data_dict, safe=False, status=200)

        else:
            return JsonResponse({'error': 'Invalid Ajax request.'}, status=400)


    return render(request, 'adventures/adventure_location/list_trips.html', {'adventure_trips': adventure_trips})


# View for detail view
def adventure_location_detail(request, location_id):
    locations_list = AdventureLocation.objects.all()
    is_ajax = request.headers.get('x-requested-with') == 'XMLHttpRequest'
    for location in locations_list:
        if (location.id == location_id):
            break

    reviews = Review.objects.filter(adventureLocation__id=location.id).order_by('-date')
    trips = AdventureTrip.objects.filter(adventureLocation__id=location.id).order_by('-date')

    if is_ajax:
        if request.method == 'POST':

            adventureId = request.POST.get('adventureId')
            review = request.POST.get('review')
            rating = request.POST.get('rating')
            theAdventure = AdventureLocation.objects.get(pk=adventureId)

            # Create a new Review object and add to DB
            nr = Review(
                adventureLocation=theAdventure,
                author=request.session.get('username'),
                review=review,
                rating=rating,
            )
            nr.save()

            # Update location review count
            location.num_reviews = location.num_reviews + 1
            location.save()


            # Log the action
            user = User.objects.get(username=request.session.get('username'))
            action = Action(
                user=user,
                verb="left a new review on:",
                target=theAdventure,
            )
            action.save()

            # Render the review section as html to send as response
            htmlToRender = render_to_string(
                template_name='adventures/adventure_location/location_detail_review.html', context={'reviews': reviews}
            )
            data_dict = {'html_from_view': htmlToRender, 'success': 'success'}
            return JsonResponse(data=data_dict, safe=False, status=200)

        else:
            return JsonResponse({'error': 'Invalid Ajax request.'}, status=400)

    return render(request,
                  'adventures/adventure_location/detail.html',
                  {
                      'location': location,
                      'adventure_trips': trips,
                      'reviews': reviews,
                  },
                  )


# View for search function
def adventure_location_search(request):
    return render(request,
                  'adventures/adventure_location/search.html',
                  )


# View for results page
def adventure_search_results(request):
    return render(request,
                  'adventures/adventure_location/search_results.html',
                  )


# Authenticate the client using your key and endpoint
def authenticate_client():
    ta_credential = AzureKeyCredential(key)
    text_analytics_client = TextAnalyticsClient(
            endpoint=endpoint,
            credential=ta_credential)
    return text_analytics_client


# View for adding location
def adventure_creator(request):
    # Redirect if not logged in
    if not request.session.get('username', False):
        return redirect('adventures:home')

    if request.method == 'POST':
        # Process the form
        main_image = request.POST.get('locationMainImage')
        name = request.POST.get('locationName')
        description = request.POST.get('locationDescription')
        alt = request.POST.get('mainImageAlt')

        # Check the data - content moderation
        endpoint = 'https://cs5774lang.cognitiveservices.azure.com/'
        key = '238baa4bb2154b73854657d97d4f244a'

        # Authenticate the client using your key and endpoint
        def authenticate_client():
            ta_credential = AzureKeyCredential(key)
            text_analytics_client = TextAnalyticsClient(
                endpoint=endpoint,
                credential=ta_credential)
            return text_analytics_client

        client = authenticate_client()

        # document to analyze
        document = [description]

        # analyze the data
        poller = client.begin_analyze_actions(
            document,
            actions=[
                ExtractSummaryAction(MaxSentenceCount=2)
            ],
        )

        # Make result into a summary
        document_results = poller.result()
        for result in document_results:
            extract_summary_result = result[0]  # first document, first result
            if extract_summary_result.is_error:
                print("...Is an error with code '{}' and message '{}'".format(
                    extract_summary_result.code, extract_summary_result.message
                ))
            else:
                response = " ".join([sentence.text for sentence in extract_summary_result.sentences])

        user = User.objects.get(username=request.session.get('username'))

        al = AdventureLocation(
            name=name,
            description=description,
            author=request.session.get('username'),
            user=user,
            img=main_image,
            alt=alt,
            summary=response,
        )
        al.save()

        # Log the action
        action = Action(
            user=user,
            verb="created the adventure location:",
            target=al,
        )
        action.save()

        messages.add_message(
            request,
            messages.SUCCESS,
            "You successfully created a new location: %s" % al.name,
        )
        return redirect('adventures:adventure_location_detail', al.id)

    else:
        # show the form
        return render(request,
                      'adventures/adventure_location/creator.html',
                      )

# View for adding trip
def trip_creator(request, location_id):
    # Redirect if not logged in
    if not request.session.get('username', False):
        return redirect('adventures:home')

    location = AdventureLocation.objects.get(id=location_id)

    if request.method == 'POST':
        # Process the form
        date = request.POST.get('date')
        name = request.POST.get('tripName')
        description = request.POST.get('tripDescription')

        # Check the data - content moderation
        endpoint = 'https://cs5774lang.cognitiveservices.azure.com/'
        key = '238baa4bb2154b73854657d97d4f244a'

        # Authenticate the client using your key and endpoint
        def authenticate_client():
            ta_credential = AzureKeyCredential(key)
            text_analytics_client = TextAnalyticsClient(
                endpoint=endpoint,
                credential=ta_credential)
            return text_analytics_client

        client = authenticate_client()

        # document to analyze
        document = [description]

        # analyze the data
        poller = client.begin_analyze_actions(
            document,
            actions=[
                ExtractSummaryAction(MaxSentenceCount=2)
            ],
        )

        # Make result into a summary
        document_results = poller.result()

templates/adventures/adventure_location/creator.html
{% extends "adventures/base.html" %}
{% load static %}

{% block page-title %}Adventure Creator{% endblock %}

<!-- Main content of page -->
{% block content %}

    <!-- The Escape-->
          <div>
            <a href="{% url 'adventures:adventure_location_list' %}">Back</a>
          </div>

          <h2>Adventure Creator</h2>

          <!-- Form to collect the adventure data -->
          <form id="create-new-adventure" action="{% url 'adventures:adventure_creator' %}" method="POST">
            {% csrf_token %}
            <!-- Upper Form Section -->
            <div id="upper-form-section">

              <!-- Hold Option Buttons -->
              <div id="option-buttons">
                <button type="submit" name="submit">Save Location</button>
              </div>

              <!-- Hold Main Item Forms-->
                <p>* = required </p>
              <div id="main-items-div">

                    <div>
                      <label for="locationMainImage">Add Main Image*</label>
                      <input type="text" id ="locationMainImage" name="locationMainImage" placeholder="Add Image URL"
                             required>
                    </div>

                  <div>
                        <label for="locationName">Location Name*</label>
                        <input type="text" name="locationName" placeholder="Add Name" required>
                  </div>

                  <div>
                        <label for="locationDescription">Description*</label>
                        <input type="textArea" id="locationDescription" name="locationDescription"
                               placeholder="Add Description" required>
                  </div>
                  <div>
                        <label for="mainImageAlt">Add Alt Text*</label>
                        <input type="text" id="mainImageAlt" name="mainImageAlt" placeholder="Image Alt Text" required>
                  </div>



              </div><!-- End main items div -->
            </div> <!-- End upper form section div -->
          </form>

{% endblock %}

templates/adventures/adventure_location/creatorTrips.html
{% extends "adventures/base.html" %}
{% load static %}

{% block page-title %}Trips Creator{% endblock %}

<!-- Main content of page -->
{% block content %}

    <!-- The Escape-->
          <div>
            <a href="{% url 'adventures:adventure_location_list' %}">Back</a>
          </div>

          <h2>Trip Creator</h2>

          <!-- Form to collect the trip data -->
          <form id="create-new-adventure" action="{% url 'adventures:trip_creator' location.id %}" method="POST">
            {% csrf_token %}
            <!-- Upper Form Section -->
            <div id="upper-form-section">

              <!-- Hold Option Buttons -->
              <div id="option-buttons">
                <button type="submit" name="submit">Save Trip</button>
              </div>

              <!-- Hold Main Item Forms-->
                <p>* = required </p>
              <div id="main-items-div">


                  <div>
                        <label for="tripName">Trip Name*</label>
                        <input type="text" name="tripName" placeholder="Add Name" required>
                  </div>

                    <div>
                      <label for="date">Date</label>
                      <input type="text" id ="date" name="date" placeholder="MM/DD/YYYY"
                             required>
                    </div>

                  <div>
                        <label for="tripDescription">Description*</label>
                        <input type="textArea" id="tripDescription" name="tripDescription"
                               placeholder="Add Description" required>
                  </div>

              </div><!-- End main items div -->
            </div> <!-- End upper form section div -->
          </form>

{% endblock %}

templates/adventures/adventure_location/creator_trips.html
{% extends "adventures/base.html" %}
{% load static %}

{% block page-title %}Trips Creator{% endblock %}

<!-- Main content of page -->
{% block content %}

    <!-- The Escape-->
          <div>
            <a href="{% url 'adventures:adventure_location_list' %}">Back</a>
          </div>

          <h2>Trip Creator</h2>

          <!-- Form to collect the trip data -->
          <form id="create-new-adventure" action="{% url 'adventures:trip_creator' location.id %}" method="POST">
            {% csrf_token %}
            <!-- Upper Form Section -->
            <div id="upper-form-section">

              <!-- Hold Option Buttons -->
              <div id="option-buttons">
                <button type="submit" name="submit">Save Trip</button>
              </div>

              <!-- Hold Main Item Forms-->
                <p>* = required </p>
              <div id="main-items-div">


                  <div>
                        <label for="tripName">Trip Name*</label>
                        <input type="text" name="tripName" placeholder="Add Name" required>
                  </div>

                    <div>
                      <label for="date">Date</label>
                      <input type="text" id ="date" name="date" placeholder="MM/DD/YYYY"
                             required>
                    </div>

                  <div>
                        <label for="tripDescription">Description*</label>
                        <input type="textArea" id="tripDescription" name="tripDescription"
                               placeholder="Add Description" required>
                  </div>

              </div><!-- End main items div -->
            </div> <!-- End upper form section div -->
          </form>

{% endblock %}

templates/adventures/adventure_location/detail.html
{% extends "adventures/base.html" %}
{% load static %}

{% block page-title %}Location Page{% endblock %}

<!-- Main content of page -->
{% block content %}

              <!-- The Escape-->
          <div class="escapeDiv">
            <a href="{% url 'adventures:adventure_location_list' %}">Back</a>

            <!-- Display only if user logged in -->
            {% if request.session.username %}
                <form action="{% url 'adventures:edit_location' location.id %}" method="GET">
                    {% csrf_token %}
                    <input type="submit" id="editLocationButton" name="edit" value="Edit">
                </form>
            {% endif %}

            <!-- Display only if user logged in as admin -->
            {% if request.session.role == 'admin' %}
                <form action="{% url 'adventures:delete_location' location.id %}" method="POST">
                    {% csrf_token %}
                    <input type="hidden" id="locationId" name="locationId" value="{{ location.id }}">
                    <input type="submit" id="deleteLocationButton" name="delete" value="Delete Location">
                </form>
            {% endif %}
          </div>

          <!-- The Location Description Section-->
          <div class="location">

            <!-- Main Location Description-->
            <div id="location-main-description">

                <div>
                  <h2>{{ location.name }}</h2>
                  {% if request.session.username %}
                    <img src="{% static "media/heart.svg" %}" class="heartIcon" alt="" id="location-page-heartIcon"> <!-- The favorite icon, from "https://www.flaticon.com/" -->
                  {% endif %}
                </div>

                <div id="main-img-div">
                  <img src="{{ location.img }}" id="location-main-img" alt="{{ location.alt }}"> <!-- Photo from blacksburg.gov https://www.blacksburg.gov/Home/Components/FacilityDirectory/FacilityDirectory/50/2512-->
                </div>

                <p> {{ location.description }} </p>
                <p>Rating: {{ location.rating }}/5</p>
                <p>{{ location.num_reviews }} - <a href="#">Reviews</a></p>
                <p>Created on {{ location.date|date:'m/d/Y' }} by <a href="
{% url 'users:profile' location.user.username %}">
                    {{ location.user.username }}</a></p>

            </div> <!-- End location-main-description div -->

            <div id="location-supporting-description">

            <!-- Display only if user logged in -->
            {% if request.session.username %}
              <!-- Upcoming Trips -->
              <div id="location-upcoming-trips">
                <div id="tripTitleDiv">
                    <h3>Upcoming Trips</h3>
                    <p><a href="{% url 'adventures:trip_creator' location.id %}">Add Trip</a></p>
                </div>

                  {% for trip in adventure_trips %}
                      {% if forloop.counter < 3 %}

                    <article>
                      <div>
                        <h4>{{ trip.name }}</h4>
                        <p>Organizer - <a href="{% url 'users:profile' trip.user.username %}">{{ trip.user.username }}</a></p>
                        <p>Date: {{ trip.date|date:'m/d/Y' }}</p>
                      </div>

                      <div>
                        <p> {{ trip.description }} </p>
                      </div>
                    </article>
                      {% endif %}

                      {% empty %}
                        <!-- Show empty message if not -->
                        <div id="empty-DB-notice-div">
                            <p id="empty-DB-notice">
                                Looks like there aren't any trips planned yet.
                            </p>
                        </div>

                  {% endfor %}

                <a href="{% url 'adventures:adventure_trip_list' %}">More Trips</a>

              </div> <!-- End location-upcoming-trips div-->
            {% endif %}

              <!-- Reviews -->
              <div id="location-reviews">
                  <h3>Reviews</h3>

                  <!-- Display only if user logged in -->
                  {% if request.session.username %}

                      <!-- Form for leaving a review on a location -->
                    <form id="detailViewReviewForm" data-ajax-url=
                            "{% url 'adventures:adventure_location_detail' location.id %}" action="" method="POST">
                        {% csrf_token %}
                        <label for="review">Leave a review:</label>
                        <br />
                        <textarea id="review" name="review" placeholder="Leave a Review"></textarea>
                        <br />
                        <label for="rating">Rate This Adventure:</label>
                        <select name="rating" id="detailViewRating">
                            <option value="1">1</option>
                            <option value="2">2</option>
                            <option value="3">3</option>
                            <option value="4">4</option>
                            <option value="5">5</option>
                        </select>
                        <br />
                        <input type="hidden" id="author" name="author" value="{{ request.session.username }}">
                        <input type="hidden" id="adventureId" name="adventureId" value="{{ location.id }}">
                        <input type="submit" id="adventureReviewSubmit" name="submit" value="Post">
                    </form>
                  {% endif %}

                  <div id="commentReviewContainer">
                      <form id="deleteReviewForm" data-ajax-url="{% url 'reviews:delete' %}"
                      action="" method="POST">
                        {% csrf_token %}
                          <input type="hidden" id="locationId" name="locationId" value="{{ location.id }}">
                        <div id="review-user">
                                <!-- Check to see if there are items in the DB to show -->
                                {% if reviews.count == 0 %}

                                    <!-- Show empty message if not -->
                                    <div id="empty-DB-notice-div">
                                        <p id="empty-DB-notice">
                                            Looks like there aren't any reviews yet. Why not leave one?
                                        </p>
                                    </div>

                                {% else %}

                                    <!-- Template to handle the review generation -->
                                    {% include 'adventures/adventure_location/location_detail_review.html' %}

                                {% endif %}

                        </div> <!-- End review-user div-->
                      </form>

                  </div>

              </div> <!-- End Location review div-->

            </div> <!-- End Supporting Description Section -->


          </div> <!-- End Location Description Section-->

{% endblock %}

templates/adventures/adventure_location/help.html
{% extends "adventures/base.html" %}
{% load static %}

{% block page-title %}Help{% endblock %}

<!-- Main content of page -->
{% block content %}

    <!-- Div to hold help info -->
    <div>
        {% if request.session.username %}
            <p>Create an adventure here: <a href="{% url 'adventures:adventure_creator' %}">Adventure Creator</a></p>

            <p>Access your profile here: <a href="{% url 'users:profile' request.session.username %}">My Profile</a></p>

            <p>Search through trips here: <a href="{% url 'adventures:adventure_trip_list' %}">List of Trips</a></p>
        {% else %}
            <p>Create an account here: <a href="{% url 'users:register' %}">Create Account</a></p>

        {% endif %}
    </div>

{% endblock %}

templates/adventures/adventure_location/home_logged_out.html
{% extends "adventures/base.html" %}
{% load static %}

{% block page-title %}Logged Out{% endblock %}

<!-- Main content of page -->
{% block content %}

        <!-- The Call-to-Action Section-->
        <div id ="callToAction">
          <h2>Start Adventuring Today</h2>

          <img src="{% static "media/outdoors.jpeg" %}" alt="the outdoors"> <!-- https://www.google.com/url?sa=i&url=http%3A%2F%2Fwhittleaway.co.uk%2Finto-the-woods-a-guide-to-the-outdoors-for-the-non-outdoorsy%2F&psig=AOvVaw0MNVrz_u3xYyrMIvFPQHW7&ust=1632259913325000&source=images&cd=vfe&ved=0CAsQjRxqFwoTCLiH5ZbAjvMCFQAAAAAdAAAAABAD -->

          <p><a href="{% url 'users:register' %}">Sign Up</a> and start adventuring today!</p>
        </div>

        <!-- Popular Adventures Section-->
        <div id="popular-adventures">
          <h3>Popular Adventures</h3>

                <!-- Dynamically Load Content for the Adventure Locations -->
                {% for location in adventure_locations %}
                  <article>
                    <img src="{{ location.img }}" alt="{{ location.alt }}"> <!-- Photo from BringFido https://photos.bringfido.com/attractions/4/2/0/13024/13024_53495.jpg?size=slide&density=1x-->

                    <div>
                      <div class="location-label">
                        <h4><a href="{% url 'adventures:adventure_location_detail' location.id %}"
          >{{ location.name }}</a></h4>
                        <p>Rating: {{ location.rating }}/5</p>
                      </div>
                    </div>

                  <!-- Display only if user logged in -->
                    {% if request.session.username %}
                    <img src="{% static "media/heart.svg" %}" class="heartIcon" alt=""> <!-- The favorite icon, from "https://www.flaticon.com/" -->
                    {% endif %}
                  </article>
                {% endfor %}

        </div> <!-- End popular-adventures div-->

{% endblock %}

templates/adventures/adventure_location/list.html
{% extends "adventures/base.html" %}
{% load static %}

{% block page-title %}Adventures{% endblock %}

<!-- Add content for the search feature section -->
{% block search-features %}

                <a href="{% url 'adventures:home' %}">Back</a>
            <h2 class="hide">Find an Adventure</h2>

            <!-- Form to search by location name -->
            <form id="search" action="" data-ajax-url="{% url 'adventures:adventure_location_list' %}" method="GET">
              <input type="submit" name="submit" value="Search">
              <input type="search" id="searchQueryString" name="search" placeholder="Find Adventures">
            </form>

            <!-- Section for Filter and add location -->
            <div id="search-filter">

                <!-- Display only if user logged in -->
                {% if request.session.username %}
                    <a href="{% url 'adventures:adventure_creator' %}">Add Adventure</a>
                {% endif %}

                <!-- Form to sort item in List View -->
                <form id="listViewSortByForm" action="" method="GET">
                    {% csrf_token %}
                  <label for="listViewSortBy">Sort by:</label>
                  <select name="listViewSortBy" id="listViewSortByList" data-ajax-url="
{% url 'adventures:adventure_location_list' %}">
                    <option value="name">Name A-Z</option>
                    <option value="-name">Name Z-A</option>
                    <option value="-rating">Rating High-Low</option>
                  </select>
                </form>

            </div>

{% endblock %}

<!-- Main content of page -->
{% block content %}

    <div id="results">

    <!-- Check to see if there are items in the DB to show -->
        {% if adventure_locations.count == 0 %}

            <!-- Show empty message if not -->
            <div id="empty-DB-notice-div">
                <p id="empty-DB-notice">
                    There are no Adventure locations right now. Please check back later.
                </p>
            </div>

        {% else %}

            <!-- Template that handles location generation -->
            {% include 'adventures/adventure_location/locations_results.html' %}

        {% endif %}
    </div>

{% endblock %}