adventures/urls.py
from django.urls import path
from . import views
app_name = 'adventures'
urlpatterns = [
    # adventure_location views
    path('', views.home, name='home'),
    path('about', views.about, name='about'),
    path('contact', views.contact, name='contact'),
    path('help', views.help, name='help'),
    path('locations', views.adventure_location_list, name='adventure_location_list'),
    path('trips', views.adventure_trip_list, name='adventure_trip_list'),
    path('locations/<int:location_id>', views.adventure_location_detail, name='adventure_location_detail'),
    path('locations/adventure-creator', views.adventure_creator, name='adventure_creator'),
    path('locations/<int:location_id>/trip-creator', views.trip_creator, name='trip_creator'),
    path('locations/adventure-editor/<int:location_id>', views.edit_location, name='edit_location'),
    path('locations/delete-location/<int:location_id>', views.delete_location, name='delete_location'),
]

djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('adventures/', include('adventures.urls', namespace='views')),
    path('users/', include('users.urls', namespace='users')),
    path('reviews/', include('reviews.urls', namespace='reviews')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views
app_name = 'users'
urlpatterns = [
    # adventure_location views
    path('register/', views.register, name='register'),
    path('profile/<str:username>', views.profile, name='profile'),
    path('login', views.login_user, name='login'),
    path('logout', views.logout_user, name='logout'),
    path('list/', views.user_list, name='list'),
    path('edit/<str:username>', views.edit_user, name='edit'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.

class Details(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    role = models.CharField(default='regular', max_length=50, null=True)


@receiver(post_save, sender=User)
def create_user_details(sender, instance, created, **kwargs):
    if created:
        Details.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_details(sender, instance, **kwargs):
    instance.details.save()

users/views.py
from django.contrib.auth import authenticate
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib import messages
from django.shortcuts import get_object_or_404


# Create your views here.
from actions.models import Action


# View to register a new account
def register(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        email = request.POST.get('email')
        user = User.objects.create_user(username, email, password)

        messages.add_message(
            request,
            messages.SUCCESS,
            "You successfully registered a new user: %s" % user.username,
        )

        # Log them in
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)

        # If user was authenticated, store info in session
        if user is not None:
            request.session['username'] = user.username
            request.session['role'] = user.details.role

        return redirect('adventures:home')
    else:
        return render(
            request,
            'users/user/register.html',
        )


# View for the profile page
def profile(request, username):
    user = get_object_or_404(User, username=username)
    user_id = user.id
    actions = Action.objects.filter(user_id__exact=user_id).order_by('-created')

    return render(
        request,
        'users/user/profile.html',
        {'user': user,
         'actions': actions},
    )


# View to login
def login_user(request):
    username = request.POST.get('username')
    password = request.POST.get('password')
    user = authenticate(username=username, password=password)

    # If user was authenticated, store info in session
    if user is not None:
        request.session['username'] = user.username
        request.session['role'] = user.details.role

        messages.add_message(
            request,
            messages.SUCCESS,
            "You have logged-in successfully as %s" % user.username,
        )

    # Else, not authenticated, invalid user
    else:
        messages.add_message(
            request,
            messages.ERROR,
            "Invalid username or password.",
        )

    return redirect('adventures:adventure_location_list')


# View to logout
def logout_user(request):
    del request.session['username']
    del request.session['role']
    messages.add_message(
        request,
        messages.SUCCESS,
        "You have successfully logged out.",
    )
    return redirect('adventures:home')


# View for admin list of users
def user_list(request):
    username = request.session.get('username')
    user = get_object_or_404(User, username=username)
    role = user.details.role

    # Display list of users to admin
    if role == 'admin':
        users = User.objects.all()
        return render(request,
                      'users/user/userList.html',
                      {'users': users},
                      )

    else:
        return redirect('adventures:home')


# View for editing user for admin
def edit_user(request, username):
    user = get_object_or_404(User, username=username)

    # Change the users role
    if request.method == 'POST':

        role = request.POST.get('role')
        password = request.POST.get('password')
        user.first_name = request.POST.get('firstName')
        user.last_name = request.POST.get('lastName')
        user.email = request.POST.get('email')

        # If there's a new password, change it
        if password != '':
            user.password = password

        # If there's a new role, change it
        if role != user.details.role and role != 'same':
            user.details.role = role
            session_user = User.objects.get(username=request.session.get('username'))

            action = Action(
                user=session_user,
                verb="changed user role of:",
                target=user,
            )
            action.save()

        user.save()
        messages.add_message(
            request,
            messages.SUCCESS,
            "%s's account successfully updated!" % username,
        )
        return redirect('users:list')

    # Else, render the edit page
    else:
        return render(request,
                      'users/user/userEdit.html',
                      {'user': user}
                      )

templates/users/user/profile.html
{% extends "adventures/base.html" %}

{% block page-title %}Profile for {{ user.username }}{% endblock %}

<!-- Main content of page -->
{% block content %}

    <h2>Profile for: {{ user.username }}</h2>

    <!-- Only show if it's the current user's profile, or an admin -->
    {% if request.session.username == user.username or request.session.role == 'admin' %}
        <a href="{% url 'users:edit' user.username %}">Edit Information</a>
    {% endif %}

    <!-- Display the activity feed -->
    <div id="activityFeedContainer">
        {% include 'actions/action/feed.html' %}
    </div>

    <!-- Display profile information -->
      <div id="profile-div">
          <div>
              <h4>Username</h4>
              <p>{{ user.username }}</p>
          </div>

          <div>
              <h4>First Name</h4>
              <p>{{ user.first_name }}</p>
          </div>

          <div>
              <h4>Last Name</h4>
              <p>{{ user.last_name }}</p>
          </div>

          <div>
              <h4>Email</h4>
              <p>{{ user.email }}</p>
          </div>

          <div>
              <h4>Role</h4>
              <p>{{ user.details.role }}</p>
          </div>


    </div><!-- End register user div -->

{% endblock %}

templates/users/user/register.html
{% extends "adventures/base.html" %}
{% load static %}

{% block page-title %}Sign Up User{% endblock %}

<!-- Main content of page -->
{% block content %}

          <h2>Sign Up</h2>

          <!-- Form to collect the adventure data -->
          <form id="registerUser" action="{% url 'users:register' %}" method="POST">
            {% csrf_token %}
            <!-- Upper Form Section -->
            <div id="upper-form-section">
              <!-- Hold Main Item Forms-->
                <p>* = required </p>
              <div id="register-user-div">

                    <div>
                      <label for="registerUsername">Username*</label>
                      <input type="text" id ="registerUsername" name="username" placeholder="Username"
                             required>
                    </div>

                  <div>
                        <label for="registerEmail">Email*</label>
                        <input type="email" name="email" placeholder="Email" required>
                  </div>

                  <div>
                        <label for="registerPassword">Password*</label>
                        <input type="password" id="registerPassword" name="password" placeholder="Password" required>
                  </div>

              </div><!-- End register user div -->

                  <!-- Hold Submit Button -->
                  <div id="register-user-submit">
                    <button type="submit" name="submit">Sign Up</button>
                  </div>
            </div> <!-- End upper form section div -->
          </form>

{% endblock %}

templates/users/user/userEdit.html
{% extends "adventures/base.html" %}

{% block page-title %}Edit User {{ user.username }}{% endblock %}

<!-- Main content of page -->
{% block content %}

    <h2>User: {{ user.username }}</h2>

              <div id="edit-user-div">
                  <form id="editUserForm" action="{% url 'users:edit' user.username %}" method="POST">
                      {% csrf_token %}

                      <div id="edit-user-div">

                            <div>
                                <label for="username">Username</label>
                                <p>{{ user.username }}</p>
                            </div>

                          <div>
                                <label for="firstName">First Name</label>
                                <input type="text" name="firstName" value="{{ user.first_name }}" required>
                          </div>

                          <div>
                                <label for="email">Last Name</label>
                                <input type="text" name="lastName" value="{{ user.last_name }}" required>
                          </div>

                          <div>
                                <label for="email">Email</label>
                                <input type="email" name="email" value="{{ user.email }}" required>
                          </div>

                          <div>
                                <label for="registerPassword">Password</label>
                                <input type="password" id="editPassword" name="password" placeholder="New Password">
                          </div>

                      <!-- Show role change if Admin -->
                      {% if request.session.role == 'admin' %}
                          <label for="role">Role: {{ user.details.role }}</label>
                          <select name="role" id="editUserList">
                              <option value="same">Don't Change</option>
                              <option value="regular">Regular</option>
                              <option value="ungregistered">Unregistered</option>
                              <option value="admin">Admin</option>
                          </select>
                          {% else %}

                          <input type="hidden" name="role" value="{{ user.details.role }}">
                      {% endif %}

                      </div><!-- End register user div -->

                                  <br />
                                  <button type="submit" name="submit">Submit</button>
                  </form>
              </div><!-- End edit user div -->

{% endblock %}

templates/users/user/userList.html
{% extends "adventures/base.html" %}
{% load static %}

{% block page-title %}User List{% endblock %}

<!-- Add content for the search feature section -->
{% block search-features %}

            <a href="{% url 'adventures:home' %}">Exit</a>
{% endblock %}

{% block content %}

    <table id="user-list-table">

        <tr>
            <th>Username</th>
            <th>Role</th>
            <th>Edit Role</th>
        </tr>

        {% for user in users %}

            <tr>
                <td><a href="{% url 'users:profile' user.username %}">{{ user.username }}</a></td>
                <td>{{ user.details.role }}</td>
                <td><a href="{% url 'users:edit' user.username %}">Edit</a></td>
            </tr>

        {% empty %}

            <li>No users stored.</li>

        {% endfor %}

    </table>

{% endblock %}